appName: "Dynamic App"

theme:
  primaryColor: "#2196F3"
  backgroundColor: "#FFFFFF"

textStyles:
  heading:
    color: "#000000"
    fontSize: 24
  body:
    color: "#333333"
    fontSize: 16

routes:
  "/":
    widget: "Scaffold"
    appBar:
      widget: "AppBar"
      title:
        widget: "Text"
        data: "Login"
    body:
      widget: "SingleChildScrollView"
      child:
        widget: "Column"
        spacing: 16
        mainAxisAlignment: "center"
        children:
          - widget: "Text"
            data: "Welcome to Dynamic App"
            style:
              color: "#2196F3"
              fontSize: 24
          - widget: "TextField"
            controller: "username"
            decoration:
              hintText: "Username"
          - widget: "TextField"
            controller: "password"
            obscureText: true
            decoration:
              hintText: "Password"
          - widget: "Checkbox"
            controller: "rememberMe"
          - widget: "Text"
            data: "Remember me"
          - widget: "ElevatedButton"
            text: "Login"
            action:
              type: "login"

  "/dashboard":
    widget: "Scaffold"
    appBar:
      widget: "AppBar"
      title:
        widget: "Text"
        data: "Dashboard"
    body:
      widget: "Column"
      spacing: 20
      children:
        - widget: "Text"
          data: "Welcome to Dashboard"
          style:
            color: "#2196F3"
            fontSize: 20
        - widget: "Row"
          children:
            - widget: "ElevatedButton"
              text: "Action 1"
              action:
                type: "showMessage"
            - widget: "Padding"
              padding: 8
              child:
                widget: "ElevatedButton"
                text: "Action 2"
                action:
                  type: "showMessage"
        - widget: "GestureDetector"
          onTap:
            type: "showMessage"
          child:
            widget: "Padding"
            padding:
              top: 16
              bottom: 16
              left: 32
              right: 32
            child:
              widget: "Text"
              data: "Tap me!"
              style:
                color: "#FF5722"
                decoration: "underline"
        - widget: "Center"
          child:
            widget: "TextButton"
            text: "Back to Login"
            onPressed:
              type: "navigate"
              route: "/"

endpoints:
  login:
    url: "https://wega.test.simetrix.ch/backend/api/v3/auth/token"
    method: "POST"
  profile:
    url: "https://api.example.com/profile"
    method: "GET"
